services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: abs-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - dagster_network

  dagster_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: dagster_code
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - dagster_network

  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    container_name: webserver
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - dagster_network
    depends_on:
      - dagster_code

  dagster_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    env_file:
      - .env
    networks:
      - dagster_network
    depends_on:
      - dagster_code

networks:
  dagster_network:
    driver: bridge
